[book]
authors = ["optimism-collective"]
language = "en"
multilingual = false
src = "specs"
title = "OP Stack Specification"

[preprocessor.katex]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/ethereum-optimism/specs"
edit-url-template = "https://github.com/ethereum-optimism/specs/edit/main/{path}"
default-theme = "ayu"
additional-js = ["specs/static/solidity.min.js", "specs/static/mermaid.min.js", "specs/static/mermaid-init.js"]
mathjax-support = true

[output.linkcheck]
